sudo: false

env:
  global:
    - secure: UcFOubx5exS33UozkL2yolgipQxl7MMYCvHLDIIUC/D6IlNiywZoDPqzVVt+nk13SsvuCqxFqySdcZRui+YcYWaWB5PCz0DUnYGtxjFLZ89JUxq25O6hXLUgit9pe0ikQSMEyKHE5SDEwuisXs1RFPjTP9Wg3eSS98o0WHRSnNAXeXsTAsFlMayzLAa/Kew+YPw57c/H2etpo9TxoXZ+RSu1cQ9JWn5yuQr7p8F7RMa+bDikye6dl3yXfHwZwISTgk9mp1ExYhXj1VAv0I6CAC97n/h6lI6jHH7o3Q082PAEqlMx7bSY7mlKDEdBVF0nsAtKpJQAZ8JG3x9cAIAmp1Ryap1ut/Tka1vSVZB7tJAj6LC8sorG7NcId31QL2Qx9qKTtbstzSxYRzQqrRcGMIAToFz+iSLfC1B2DgUF6S9OM/fLkb21+ByzBfeTtUgR7bYSErDXB5Ze53r54/YNNwxtSomJ5TLeJx5zfMn5z4UIULsEUEECtrdbHimB2gf2BEJUKZHDbyKVvIFY14Jf/v2cyUbIZtYxneeYu2hraV3+bcFURr6uGtr/Csqc0rtXdrurW/x9gJ31aVyDIdpzZHkQEkqwNKXW/HiI9TZXgSa254MeM4oscjbPBAVUZkvkR55j+tdU7hFCKvrM1WcCuzl1XneojuemVGBwIzXghHk=

cache:
  apt: true
  directories:
    - ~/.stack

branches:
  only:
    - master
    - develop

before_install:
    - export PATH=/opt/ghc/$GHCVER/bin:$PATH
    - export PATH=~/.local/bin:$PATH
    - ./script/travis-lifecycle-before_install

install:
    - ./script/travis-lifecycle-install

script:
    - ./script/travis-lifecycle-script

matrix:
  fast_finish: true
  include:
    - env: GHCVER=8.0.1 LIBRARY=documentation
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }
    - env: GHCVER=8.0.1 LIBRARY=credentials
      addons: { apt: { packages: [ghc-8.0.1], sources: [hvr-ghc] } }

