resolver:   nightly-2015-08-17
flags:      {}
extra-deps: []
packages:
  - credentials
  - credentials-cli
  - credentials-dynamodb
  - ../amazonka/amazonka
  - ../amazonka/core
  - ../amazonka/amazonka-dynamodb
  - ../amazonka/amazonka-kms
  - ../amazonka/amazonka-s3