#!/usr/bin/env bash

set -e

store="$1"

if [ -z "$store" ]; then
    echo "Usage: run <STORE>"
    exit 1
fi

region="eu-central-1"

send() {
    local mode="$1"
    local args="$2"

    credentials $mode -r $region -u $store $args
}

gets() {
    local name="$1"
    local expect="$2"
    local context="$3"

    local actual="$(credentials get -r $region -u $store --name $name $context)"

    if [ "$expect" != "$actual" ]; then
        send "list"
        echo "Test failed for $name, expected: $expect, actual: $actual"
        send "get" "--name $name $context --format json"
        echo ""
        exit 1
    fi
}

puts() {
    local name="$1"
    local secret="$2"
    local context="$3"

    credentials put -r $region -u $store --name $name -s "$secret" $context
    gets "$name" "$secret" "$context"
}

send "cleanup" "-f"
send "setup"

echo 'Put series'

puts "foo" "secret"
puts "foo" "not so secret"
puts "foo" "something"
puts "foo" "bother"

echo 'Delete revision 3'

send "delete" "--name foo --revision 3 -f"
gets "foo" "bother"

echo 'Delete revision 4'

send "delete" "--name foo --revision 4 -f"
gets "foo" "not so secret"

echo 'Put with context'

puts "bar" "longer secret" "-c a=b -c this=notthis"

send "list"

echo "Done."
